config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  devise_for :users, path: 'account', controllers: {
      sessions: 'users/sessions', registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords'
  }
  mount RuCaptcha::Engine => '/rucaptcha'
  resources :accounts, only: [:new, :create, :destroy] do
    collection do
      get :register
      post :register_post
      post :validate_captcha
      get :forget_password
      get :reset_password
      post :reset_password_post
      post :send_code
      post :register_email_exists
      post :register_mobile_exists
      post :register_nickname_exists
    end
  end

  get 'user' => redirect('/user/preview')

  match 'user/preview' => 'user#preview', as: 'user_preview', via: [:get, :post]
  match 'user/profile' => 'user#profile', as: 'user_profile', via: [:get, :post]
  match 'user/update_avatar' => 'user#update_avatar', as: 'user_update_avatar', via: [:post]
  match 'user/remove_avatar' => 'user#remove_avatar', as: 'user_remove_avatar', via: [:post]
  match 'user/passwd' => 'user#passwd', as: 'user_passwd', via: [:get, :post]
  match 'user/reset_mobile' => 'user#reset_mobile', as: 'user_reset_mobile', via: [:get, :post]
  match 'user/reset_email' => 'user#reset_email', as: 'user_reset_email', via: [:get, :post]
  match 'user/send_email_code' => 'user#send_email_code', as: 'user_send_email_code', via: [:post]
  match 'user/send_add_mobile_code' => 'user#send_add_mobile_code', as: 'user_send_add_mobile_code', via: [:post]
  match 'user/comp' => 'user#comp', as: 'user_comp', via: [:get]
  match 'user/consult' => 'user#consult', as: 'user_consult', via: [:get, :post]
  match 'user/point' => 'user#point', as: 'user_point', via: [:get, :post]
  match 'user/add_point' => 'user#add_point', as: 'user_add_point', via: [:get, :post]
  match 'user/notification' => 'user#notification', as: 'user_notification', via: [:get]
  get '/user/notify' => 'user#notify_show'
  match '/user/add_school' => 'user#add_school', as: 'user_add_school', via: [:post]


  # mount ActionCable.server => '/cable'
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  # 个人信息概览
  def preview
    @user_info = User.joins('left join user_profiles u_p on u_p.user_id = users.id').joins('left join schools s on s.id = u_p.school_id').where(id: current_user.id).select(:email, :mobile, 'u_p.username as name', 'u_p.gender', 'u_p.grade', 'u_p.bj', 'u_p.roles as role', 'u_p.birthday', 's.name as school', 'u_p.address').take
  end


  # 修改个人信息
  def profile
    # 获取Profile
    @user_profile = current_user.user_profile ||= current_user.build_user_profile
    @th_role_status = UserRole.where(user_id: current_user.id, role_id: 1).first # 教师
    if request.method == 'POST'
      if params[:user_profile].present?
        # 过滤Profile参数
        profile_params = params.require(:user_profile).permit(:username, :school, :bj, :gender, :birthday, :address, :teacher_no, :certificate, :grade, :autograph, {:roles => []}).tap do |list|
          if params[:user_profile][:roles].present? && params[:user_profile][:roles] != '教师'
            list[:roles] = params[:user_profile][:roles].join(',')
          else
            list[:roles] = nil
          end
        end
        if ['高一', '高二', '高三'].include?(profile_params[:grade])
          unless /^[1-9]\d{5}[1-9]\d{3}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}([0-9]|X)$/.match(profile_params[:identity_card]) != nil
            flash[:error] = '高中生请正确填写18位身份证号'
            return false
          end
        end
        message = ''
        if profile_params[:roles].present? && profile_params[:roles].include?('教师')
          unless profile_params[:teacher_no].present? && profile_params[:certificate].present? && profile_params[:school].present? && profile_params[:username].present?
            flash[:error] = '选择教师身份时，请填写姓名、学校、教师编号、和上传教师证件'
            return false
          end
          unless UserRole.where(user_id: current_user.id, role_id: 1).exists?
            th_role = UserRole.create!(user_id: current_user.id, role_id: 1, status: false) # 教师
            if th_role.save
              message = '您的老师身份已提交审核，审核通过后会在［消息］中告知您！'
            else
              message
            end
          end
        end
        if message=='-'
          message=''
        end
        puts 'nihao'
        puts profile_params[:username]
        puts @user_profile.user_id
        @user_profile.username = profile_params[:username]
        @user_profile.autograph = profile_params[:autograph]
        @user_profile.school_id = profile_params[:school].to_i
        @user_profile.district_id = profile_params[:district_id].to_i
        @user_profile.grade = profile_params[:grade]
        @user_profile.bj = profile_params[:bj]
        @user_profile.age = profile_params[:age]
        @user_profile.birthday = profile_params[:birthday]
        @user_profile.gender = profile_params[:gender].to_i
        @user_profile.address = profile_params[:address]
        @user_profile.roles = profile_params[:roles]
        @user_profile.teacher_no = profile_params[:teacher_no]
        @user_profile.certificate = profile_params[:certificate]
        if @user_profile.save
          flash[:success] = '更新成功'+message
        else
          flash[:error] = '更新失败'+message
        end
      else
        flash[:error] = '不能提交空信息'
      end
      redirect_to user_profile_path
    end
  end

  def check_email_exists
    render json: require_email
  end

  def check_mobile_exists
    render json: require_mobile
  end

  def check_email_and_mobile
    render json: require_email_and_mobile
  end

  def email
    if params[:return_uri].present?
      return_uri = params[:return_uri]
      session[:return_apply_event] = return_uri
    end
    if request.method == 'POST'
      current_user.email = params[:user][:email]
      ec = EmailService.new(params[:user][:email])
      status, message = ec.validate?(params[:email_code], EmailService::TYPE_CODE_ADD_EMAIL_CODE)
      if status
        current_user.email = params[:user][:email]
        if current_user.save
          flash[:success] = '邮箱添加成功'
          if session[:return_apply_event].present?
            redirect_to session[:return_apply_event]
            session[:return_apply_event] = nil
          else
            redirect_to user_preview_path
          end
        else
          flash[:error] = '邮箱添加失败'
        end
      else
        current_user.email = params[:user][:email]
        flash[:error] = message
      end
    end
  end

  def mobile
    if request.method == 'POST'
      current_user.mobile_info = params[:user][:mobile_info]
      sms = SMSService.new(params[:user][:mobile_info])
      status, message = sms.validate?(params[:email_code], SMSService::TYPE_CODE_ADD_MOBILE)
      if status
        current_user.mobile = params[:user][:mobile_info]
        if current_user.save
          flash[:success] = '手机添加成功'
          redirect_to user_preview_path
        else
          flash[:error] = '手机添加失败'
        end
      else
        current_user.mobile_info = params[:user][:mobile_info]
        flash[:error] = message
      end
    end
  end

  def reset_mobile
    if params[:mobile_info].present?
      current_user.mobile_info = params[:mobile_info]
    end
    if params[:email_code].present?
      current_user.email_code = params[:email_code]
    end
    if request.method == 'POST' && verify_rucaptcha?(current_user)
      unless params[:mobile_info].present? && params[:email_code].present? && params[:password].present?
        flash[:error] = '请将手机号、手机验证码、密码填写完整'
        return
      end
      unless current_user.valid_password?(params[:password])
        flash[:error]='密码不正确'
        return
      end
      sms = SMSService.new(params[:mobile_info])
      status, message = sms.validate?(params[:email_code], SMSService::TYPE_CODE_ADD_MOBILE)
      if status
        current_user.mobile = params[:mobile_info]
        if current_user.save
          flash[:success] = '手机更新成功'
          redirect_to user_preview_path
        else
          flash[:error] = '手机更新失败'
        end
      else
        flash[:error] = message
      end
    end
  end

  def reset_email
    if params[:email_info].present?
      current_user.email_info = params[:email_info]
    end
    if params[:email_code].present?
      current_user.email_code = params[:email_code]
    end
    if request.method == 'POST' && verify_rucaptcha?(current_user)
      unless params[:email_info].present? && params[:email_code].present? && params[:password].present?
        flash[:error] = '请将邮箱、邮箱验证码、密码填写完整'
        return
      end
      unless current_user.valid_password?(params[:password])
        flash[:error]='密码不正确'
        return
      end
      es = EmailService.new(params[:email_info])
      status, message = es.validate?(params[:email_code], EmailService::TYPE_CODE_ADD_EMAIL_CODE)
      if status
        current_user.email = params[:email_info]
        if current_user.save
          flash[:success] = '邮箱更新成功'
          redirect_to user_preview_path
        else
          flash[:error] = '邮箱更新失败'
        end
      else
        flash[:error] = message
      end
    end
  end

  def comp
  end

  # def consult
  #   if request.method == 'POST'
  #     content = params[:consult][:content]
  #     if content.present? && content.length < 151 && content.length > 5
  #       consult = Consult.create(user_id: current_user.id, content: content)
  #       if consult.save
  #         flash[:success]='调戏成功'
  #         redirect_to user_consult_path
  #       else
  #         flash[:error]='提交失败'
  #       end
  #     else
  #       @consult = Consult.new(content: params[:consult][:content])
  #       flash[:error]='请填写6-150位字符的反馈内容'
  #     end
  #   end
  #   unless @consult.present?
  #     @consult = current_user.consults.build
  #   end
  #   @consults = Consult.where(user_id: current_user.id).all.order('id asc')
  # end

  # def point
  #   @user_points = UserPoint.joins(:prize).where(user_id: current_user.id).select(:id, :is_audit, 'prizes.name', 'prizes.host_year', 'prizes.point', 'prizes.prize')
  # end

  # def add_point
  #   @point = current_user.user_points.build
  #   if request.method == 'POST'
  #     u_p = UserPoint.create(user_id: current_user.id, prize_id: params[:user_point][:prize_id], cover: params[:user_point][:cover])
  #     if u_p.save
  #       flash[:success] = 'ok'
  #       redirect_to user_point_path
  #     else
  #       flash[:error] = 'fail'
  #     end
  #   end
  # end


  def notification
    @notifications = current_user.notifications.page(params[:page]).per(params[:per]).order('created_at desc')
    if params[:id].present?
      @notification = Notification.find(params[:id])
    end
  end

  def notify_show
    @notification = current_user.notifications.where(id: params[:id]).take

    if @notification.present?

    end
  end


  def passwd
    if request.method == 'POST'
      status, message = self.change_password(params[:user][:old_password], params[:user][:new_password], params[:user][:password_confirmation])
      if status
        flash[:success] = message
        redirect_to new_user_session_path
      else
        flash[:error] = message
      end
    end
  end


  # 更新头像和 nickname
  def update_avatar
    if params[:user].present?
      if current_user.update_attributes(params.require(:user).permit(:nickname, :avatar))
        flash[:success] = '个人信息更新成功'
      elsif User.where(nickname: params[:user][:nickname]).where.not(id: current_user.id).take.present?
        flash[:error] = params[:user][:nickname]+'已被使用,请使用其他昵称!'
      else
        flash[:error] = '个人信息更新失败'
      end
    else
      flash[:error] = '昵称不能为空'
    end
    redirect_to user_preview_path
  end

  # 头像删除
  def remove_avatar
    if current_user.avatar?
      current_user.remove_avatar!
      current_user.avatar = nil
      current_user.save
      flash[:success] = '头像已成功删除'
    end
    redirect_to user_profile_path
  end

  def add_school
    name = params[:school]
    district = params[:district]

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    if verify_rucaptcha?(resource)
      self.resource = resource_class.send_reset_password_instructions(resource_params)
      yield resource if block_given?
      if successfully_sent?(resource)
        respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
      else
        respond_with(resource)
      end
    else
      self.resource = resource_class.new
      resource.email = params[resource_name][:email]
      resource.status = 1000
      render 'new'
    end
  end
  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

# GET /resource/sign_in
# def new
#   super
# end

# POST /resource/sign_in
  def create
    # super
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_flashing_format?
    sign_in(resource_name, resource)
    current_user.update_attribute(:private_token, "#{SecureRandom.uuid.gsub('-', '')}")
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

# DELETE /resource/sign_out
  def destroy
    current_user.update_attributes(private_token: nil)
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message :notice, :signed_out if signed_out && is_flashing_format?
    yield if block_given?
    respond_to_on_destroy
  end

# protected

# If you have extra params to permit, append them to the sanitizer.
# def configure_sign_in_params
#   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
# end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/_tab.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li <%= 'class=active' if action_name == 'preview' %>>
    <a href="<%= user_preview_path %>"><span class="hidden-xs">信息</span>概览</a>
  </li>

  <li <%= 'class=active' if action_name == 'profile' %>>
    <a href="<%= user_profile_path %>"><span class="hidden-xs">个人</span>资料</a>
  </li>
  <li <%= 'class=active' if action_name == 'passwd' %>>
    <a href="<%= user_passwd_path %>"><span class="hidden-xs">修改</span>密码</a>
  </li>
  <li <%= 'class=active' if action_name == 'reset_mobile' %>>
    <a href="<%= user_reset_mobile_path %>"><span class="hidden-xs">修改</span>手机号</a>
  </li>
  <li <%= 'class=active' if action_name == 'reset_email' %>>
    <a href="<%= user_reset_email_path %>"><span class="hidden-xs">修改</span>邮箱</a>
  </li>
</ul>
<br>

app/views/user/preview.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-3 hidden-xs">
      <%= render 'user/menu' %>
    </div>
    <div class="col-xs-12 col-sm-9">
      <h1 class="page-header">
        我的账户
      </h1>

      <%= render 'user/tab' %>
      <div class="panel panel-default">
        <div class="panel-body">
          <%= link_to user_profile_path do %>
              <%= image_tag(current_user.avatar_url(:middle), class: 'img-thumbnail') %>
          <% end %>
        </div>
        <ul class="list-group">

          <li class="list-group-item">
            昵称：<a href="<%= user_profile_path %>"><%= current_user.nickname %></a>
          </li>


          <% if @user_info.present? %>
              <li class="list-group-item">
                姓名：<%= @user_info.name %>
              </li>
              <li class="list-group-item">
                性别：
                <% if @user_info.gender == 1 %>男
                <% elsif @user_info.gender == 2 %>女
                <% else %>
                <% end %>
              </li>
              <li class="list-group-item">
                生日：<%= @user_info.birthday %>
              </li>

              <li class="list-group-item">
                地址：<%= @user_info.address %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/user/profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-3 hidden-xs">
      <%= render 'user/menu' %>
    </div>
    <div class="col-xs-12 col-sm-9">
      <h1 class="page-header">
        我的账户
      </h1>

      <%= render 'user/tab' %>
      <div class="panel panel-default">
        <div class="panel-body">
          <%= simple_form_for(current_user, html: {id: 'form_change_avatar', multipart: true}, url: user_update_avatar_path, method: :post) do |f| %>
              <div class="form-inputs">
                <div class="row">
                  <div class="col-sm-4">
                    <div class="form-group">
                      <p>
                        <%= image_tag(current_user.avatar_url(:middle), class: 'img-thumbnail') %>
                      </p>
                      <% if current_user.avatar? %>
                          <%= link_to '删除头像', user_remove_avatar_path, data: {method: :post, confirm: '确认删除头像吗？'}, class: 'btn btn-danger' %>
                      <% end %>
                    </div>
                  </div>
                  <div class="col-sm-8">
                    <div class="form-group">
                      <label for="user_avatar">选择头像</label>
                      <%= f.file_field :avatar %>
                      <p class="help-block">格式：jpg jpeg gif png，尺寸：400x400</p>
                    </div>
                    <%= f.hidden_field :avatar_cache %>
                    <%= f.input :nickname %>
                    <div class="form-actions">
                      <%= f.button :submit, class: 'btn btn-primary', value: '更新昵称和头像', 'data-disable-with': '更新昵称和头像' %>
                    </div>
                  </div>
                </div>
              </div>
          <% end %>
          <hr>
          <h3 class="sub-header">详细信息</h3>
          <%= simple_form_for(@user_profile, html: {id: 'form_change_profile', multipart: true}, url: user_profile_path, method: :post) do |f| %>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-inputs">
                    <%= f.input :username %>
                    <div class="form-group string optional user_profile_roles">
                      <label class="string optional control-label" for="user_profile_roles">身份</label>

                      <div>
                        <% Role.all.each do |r| %>
                            <% if r.name=='教师' && @th_role_status.present? %>
                                <%= label_tag '老师' %> <%= "(待审核)" if @th_role_status.status.blank? %>
                            <% else %>
                                <%= check_box_tag 'user_profile[roles][]', r.name, (true if @user_profile.roles.present? && @user_profile.roles.split(',').include?(r.name.to_s)) %>
                                <%= label_tag r.name %>
                            <% end %>
                        <% end %>
                      </div>
                    </div>
                    <div class="teacher-part hide">
                      <%= f.input :teacher_no %>
                    </div>
                    <div class="form-group teacher-part hide">
                      <label for="user_avatar">上传教师证</label>
                      <%= f.file_field :certificate %>
                    </div>

                    <%= f.input :district_id, label: '区县' %>
                    <%= f.input :school_id, label: '学校' %>
                    <%= f.input :grade %>
                    <%= f.input :bj %>
                    <%= f.input :gender, collection: UserProfile::GENDER.map { |key, val| [t('gender.'+key.to_s), val] } %>
                    <%= f.input :birthday, as: :date, html5: true %>
                    <%= f.input :address %>
                  </div>
                  <div class="form-actions">
                    <%= f.button :submit, class: 'btn btn-primary', value: '更新详细信息', 'data-disable-with': '更新详细信息' %>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>