config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  devise_for :users, path: 'account', controllers: {
      sessions: 'users/sessions', registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords'
  }
  mount RuCaptcha::Engine => '/rucaptcha'
  resources :accounts, only: [:new, :create, :destroy] do
    collection do
      get :register
      post :register_post
      post :validate_captcha
      get :forget_password
      get :reset_password
      post :reset_password_post
      post :send_code
      post :register_email_exists
      post :register_mobile_exists
      post :register_nickname_exists
    end
  end

  get 'user' => redirect('/user/preview')

  match 'user/preview' => 'user#preview', as: 'user_preview', via: [:get, :post]
  match 'user/profile' => 'user#profile', as: 'user_profile', via: [:get, :post]
  match 'user/update_avatar' => 'user#update_avatar', as: 'user_update_avatar', via: [:post]
  match 'user/remove_avatar' => 'user#remove_avatar', as: 'user_remove_avatar', via: [:post]
  match 'user/passwd' => 'user#passwd', as: 'user_passwd', via: [:get, :post]
  match 'user/reset_mobile' => 'user#reset_mobile', as: 'user_reset_mobile', via: [:get, :post]
  match 'user/reset_email' => 'user#reset_email', as: 'user_reset_email', via: [:get, :post]
  match 'user/send_email_code' => 'user#send_email_code', as: 'user_send_email_code', via: [:post]
  match 'user/send_add_mobile_code' => 'user#send_add_mobile_code', as: 'user_send_add_mobile_code', via: [:post]
  match 'user/comp' => 'user#comp', as: 'user_comp', via: [:get]
  match 'user/consult' => 'user#consult', as: 'user_consult', via: [:get, :post]
  match 'user/point' => 'user#point', as: 'user_point', via: [:get, :post]
  match 'user/add_point' => 'user#add_point', as: 'user_add_point', via: [:get, :post]
  match 'user/notification' => 'user#notification', as: 'user_notification', via: [:get]
  get '/user/notify' => 'user#notify_show'
  match '/user/add_school' => 'user#add_school', as: 'user_add_school', via: [:post]


  # mount ActionCable.server => '/cable'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>豆姆智能科技 － 管理后台</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track' => false %>
</head>
<body>
<% if notice.present? %>
    <div id="notice"><%= notice %></div>
<% end %>
<% if alert.present? %>
    <div id="alert"><%= alert %></div>
<% end %>
<div class="navbar navbar-default" id="navbar">
  <div class="navbar-container" id="navbar-container">
    <div class="navbar-header pull-left">
      <a href="/admin" class="navbar-brand">
        <small><i class="icon-leaf"></i> 豆姆科技管理后台</small>
      </a>
    </div>
    <div class="navbar-header pull-right" role="navigation">
      <ul class="nav ace-nav">
        <li class="grey">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <i class="icon-tasks"></i>
            <span class="badge badge-grey">0</span>
          </a>
        </li>
        <li class="purple">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <i class="icon-bell-alt icon-animated-bell"></i>
            <span class="badge badge-important">0</span>
          </a>
          <!--<ul class="pull-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">-->
          <!--<li class="dropdown-header">-->
          <!--<i class="icon-warning-sign"></i>-->
          <!--共有 0 个身份待审核-->
          <!--</li>-->

          <!--<li>-->
          <!--<a href="/admin/checks/teachers">-->
          <!--<div class="clearfix">-->
          <!--<span class="pull-left">-->
          <!--老师-->
          <!--</span>-->
          <!--<span class="pull-right badge badge-info">+0</span>-->
          <!--</div>-->
          <!--</a>-->
          <!--</li>-->

          <!--<li>-->
          <!--<a href="/admin/checks/referees">-->
          <!--<div class="clearfix">-->
          <!--<span class="pull-left">-->
          <!--裁判-->
          <!--</span>-->
          <!--<span class="pull-right badge badge-success">+0</span>-->
          <!--</div>-->
          <!--</a>-->
          <!--</li>-->

          <!--<li>-->
          <!--<a href="#">-->
          <!--暂不审核-->
          <!--<i class="icon-arrow-right"></i>-->
          <!--</a>-->
          <!--</li>-->
          <!--</ul>-->

        </li>

        <li class="green">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <i class="icon-envelope icon-animated-vertical"></i>
            <span class="badge badge-success">0</span>
          </a>
        </li>
        <li class="light-blue">
          <a data-toggle="dropdown" href="#" class="dropdown-toggle" style="min-width: 112px">
            <span class="user-info">
                <small>欢迎登录</small>
              <%= @current_admin.job_number %><%= " - #{ @current_admin.name }" if @current_admin.name.present? %>
            </span>
            <i class="icon-caret-down"></i>
          </a>
          <ul class="dropdown-admin-layout user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close" style="min-width: 114px;right: -1px">
            <li>
              <a href="<%= change_password_admin_accounts_path %>">
                <i class="icon-cog"></i>
                修改密码
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#">
                <i class="icon-user"></i>
                个人信息
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to admin_account_path(@current_admin), method: :delete, data: {confirm: '确认退出吗？'}, title: '退出登录', class: '' do %>
                  <i class="icon-off"></i>
                  退出登录
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="main-container" id="main-container">
  <div class="main-container-inner">
    <a class="menu-toggler" id="menu-toggler" href="#">
      <span class="menu-text"></span>
    </a>

    <div class="sidebar" id="sidebar">
      <script type="text/javascript">
        try {
          ace.settings.check('sidebar', 'fixed')
        } catch (e) {
        }
      </script>
      <div class="sidebar-shortcuts" id="sidebar-shortcuts">
        <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
          <button class="btn btn-success">
            <i class="icon-signal"></i>
          </button>

          <button class="btn btn-info">
            <i class="icon-pencil"></i>
          </button>

          <button class="btn btn-warning">
            <i class="icon-group"></i>
          </button>

          <button class="btn btn-danger">
            <i class="icon-cogs"></i>
          </button>
        </div>

        <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
          <span class="btn btn-success"></span>

          <span class="btn btn-info"></span>

          <span class="btn btn-warning"></span>

          <span class="btn btn-danger"></span>
        </div>
      </div>
      <!-- #sidebar-shortcuts -->
      <ul class="nav nav-list">
        <li class="<%= params[:controller] == 'admin/users' ? 'active' : '' %>">
          <a href="<%= admin_users_path %>">
            <i class="icon-user"></i>
            <span class="menu-text"> 用户 </span>
          </a>
        </li>
        <li class="<%= params[:controller] == 'admin/admins' ? 'active' : '' %>">
          <a href="<%= admin_admins_path %>">
            <i class="icon-gear"></i>
            <span class="menu-text"> 管理员 </span>
          </a>
        </li>
        <li class="<%= params[:controller] == 'admin/organizers' ? 'active' : '' %>">
          <a href="<%= admin_organizers_path %>">
            <i class="icon-home"></i>
            <span class="menu-text"> 单位 </span>
          </a>
        </li>
        <li class="<%= params[:controller] == 'admin/districts' ? 'active' : '' %>">
          <a href="<%= admin_districts_path %>">
            <i class="icon-globe"></i>
            <span class="menu-text"> 区县 </span>
          </a>
        </li>
        <li class="<%= params[:controller] == 'admin/schedules' ? 'active' : '' %>">
          <a href="<%= admin_schedules_path %>">
            <i class="icon-calendar"></i>
            <span class="menu-text"> 赛程名 </span>
          </a>
        </li>
        <li class="<%= params[:controller] == 'admin/roles' ? 'active' : '' %>">
          <a href="<%= admin_roles_path %>">
            <i class="icon-leaf"></i>
            <span class="menu-text"> 角色 </span>
          </a>
        </li>
        <li class="<%= params[:controller] == 'admin/news_types' ? 'active' : '' %>">
          <a href="<%= admin_news_types_path %>">
            <i class="icon-list"></i>
            <span class="menu-text"> 新闻类型 </span>
          </a>
        </li>
        <li class="<%= params[:controller] == 'admin/news' ? 'active' : '' %>">
          <a href="<%= admin_news_index_path %>">
            <i class="icon-comment-alt"></i>
            <span class="menu-text"> 新闻 </span>
          </a>
        </li>
        <li class="<%= params[:controller] == 'admin/competitions' ? 'active' : '' %>">
          <a href="<%= admin_competitions_path %>">
            <i class="icon-beaker"></i>
            <span class="menu-text"> 比赛 </span>
          </a>
        </li>
        <li class="<%= params[:controller] == 'admin/events' ? 'active' : '' %>">
          <a href="<%= admin_events_path %>">
            <i class="icon-hand-right"></i>
            <span class="menu-text"> 项目 </span>
          </a>
        </li>
        <li class="<%= params[:controller] == 'admin/score_attributes' ? 'active' : '' %>">
          <a href="<%= admin_score_attributes_path %>">
            <i class="icon-hdd"></i>
            <span class="menu-text"> 成绩属性 </span>
          </a>
        </li>
        <li class="<%= params[:controller] == 'admin/activities' ? 'active' : '' %>">
          <a href="<%= admin_activities_path %>">
            <i class="icon-gift"></i>
            <span class="menu-text"> 活动 </span>
          </a>
        </li>
        <li class="<%= params[:controller] == 'admin/volunteers' ? 'active' : '' %>">
          <a href="<%= admin_volunteers_path %>">
            <i class="icon-glass"></i>
            <span class="menu-text"> 志愿者 </span>
          </a>
        </li>
        <li class="<%= params[:controller] == 'admin/consults' ? 'active' : '' %>">
          <a href="<%= admin_consults_path %>">
            <i class="icon-comments"></i>
            <span class="menu-text"> 用户反馈 </span>
          </a>
        </li>
        <!--<li class="<%= params[:controller] == 'admin/demeanor' ? 'active' : '' %>">-->
        <!--<a href="<%= admin_photos_path %>">-->
        <!--<i class="icon-camera"></i>-->
        <!--<span class="menu-text"> 选手风采 </span>-->
        <!--</a>-->
        <!--</li>-->

      </ul>
      <!-- /.nav-list -->
      <div class="sidebar-collapse" id="sidebar-collapse">
        <i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
      </div>
      <script type="text/javascript">
        try {
          ace.settings.check('sidebar', 'collapsed')
        } catch (e) {
        }
      </script>
    </div>
    <div class="main-content">
      <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
          <li>
            <i class="icon-home home-icon"></i>
            <a href="/admin">首页</a>
          </li>
        </ul>
        <!-- .breadcrumb -->
      </div>
      <div class="page-content">
        <%= yield %>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
<script type="text/javascript">
  jQuery(function ($) {
    var color_box_params = {
      reposition: true,
      scalePhotos: true,
      scrolling: false,
      previous: '<i class="icon-arrow-left"></i>',
      next: '<i class="icon-arrow-right"></i>',
      close: '&times;',
      current: '{current} / {total}',
      maxWidth: '100%',
      maxHeight: '100%',
      onOpen: function () {
        document.body.style.overflow = 'hidden';
      },
      onClosed: function () {
        document.body.style.overflow = 'auto';
      },
      onComplete: function () {
        $.colorbox.resize();
      }
    };
    $('.ace-thumbnails [data-rel="colorbox"]').colorbox(color_box_params);
    $("#cboxLoadingGraphic").append("<i class='icon-spinner orange'></i>");//loading icon
  })
</script>
</body>
</html>

app/views/layouts/admin_boot.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>豆姆科技 － 后台登陆</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=false">-->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>
  <%= notice %><%= alert %>
</p>
<%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render_page_title %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <link rel="icon" href="<%= asset_path('icon.png') %>"/>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>

</head>

<body>
<div class="navbar-wrapper">
  <nav class="navbar navbar-default nav-custom navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand navbar-padding" href="/">豆姆科技</a>
        <!-- begin visible xs -->
        <% if user_signed_in? %>

            <span class="navbar-padding navbar-brand pull-right visible-xs btn" data-toggle="collapse" data-target="#navbar_user" aria-expanded="false" aria-controls="navbar">
              <span class="caret"></span>
            </span>
        <% else %>
            <a class="navbar-brand pull-right visible-xs" href="<%= new_user_registration_path %>">注册</a>
            <a class="navbar-brand pull-right visible-xs" href="<%= new_user_session_path %>">登录</a>

        <% end %>
        <!-- end visible xs -->
      </div>
      <!-- begin hidden xs -->
      <ul class="nav navbar-nav navbar-right hidden-xs">
        <% if user_signed_in? %>
            <li>
              <a href="<%= "#" %>">
                <i class="glyphicon glyphicon-bell"></i>
                <% if current_user.notifications.unread.count > 0 %>
                    <span class="badge"><%= current_user.notifications.unread.count %></span>
                <% end %>
              </a>
            </li>


            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.nickname %>
                <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% if current_user %>
                    <li>
                      <a href="<%= user_preview_path %>">个人信息<span class="visible-xs pull-right">[ <%= current_user.nickname %>
                        ]</span></a>
                    </li>
                    <li class="nav-divider visible-xs"></li>
                    <li class="divider hidden-xs"></li>
                    <li>
                      <a href="#">消息通知</a>
                    </li>
                    <li class="nav-divider visible-xs"></li>

                <% end %>
              </ul>
            </li>
            <li>
              <%= link_to '退出', destroy_user_session_path, method: :delete, data: {confirm: '确认退出登录吗?'} %>
            </li>
        <% else %>
            <li><%= link_to '注册', new_user_registration_path %></li>
            <li><%= link_to '登录', new_user_session_path %></li>
        <% end %>
      </ul>
      <!-- end hidden xs -->
      <!-- begin main menu -->
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav nav-li">
          <li>
            <a href="<%= "#" %>">比赛</a>
          </li>
          <li class="nav-divider"></li>
          <li>
            <a href="<%= "#" %>">课程</a>
          </li>

        </ul>
      </div>
      <!-- end main menu -->
      <!-- begin user menu visible xs -->
      <div id="navbar_user" class="navbar-collapse collapse">
        <ul class="nav navbar-nav visible-xs">
          <% if current_user %>
              <li>
                <a href="<%= "#" %>">我的账户<span class="visible-xs pull-right">[ <%= current_user.nickname %>
                  ]</span></a>
              </li>
              <li class="nav-divider visible-xs"></li>
              <li class="divider hidden-xs"></li>
              <li>
                <a href="#">我的收藏</a>
              </li>
              <li class="nav-divider visible-xs"></li>
              <li class="divider hidden-xs"></li>

          <% end %>
        </ul>
      </div>
      <!-- end user menu -->
    </div>
  </nav>
</div>

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<% if flash.present? %>
    <script type="text/javascript">
      <% flash.each do |f| %>
      $.notify("<%= f[1] %>", "<%= f[0] %>");
      <% end %>
    </script>
<% end %>

<% if current_user %>
    <script type="text/javascript" charset="utf-8">

      $(function () {
        function notify(title, content) {
          if (!title && !content) {
            title = "桌面提醒";
            content = "您看到此条信息桌面提醒设置成功";
          }
          var iconUrl = "/assets/icon.png";
          if (window.webkitNotifications) {
            //chrome老版本
            if (window.webkitNotifications.checkPermission() == 0) {
              var notif = window.webkitNotifications.createNotification(iconUrl, title, content);
              notif.display = function () {
              };
              notif.onerror = function () {
              };
              notif.onclose = function () {
              };
              notif.onclick = function () {
                this.cancel();
              };
              notif.replaceId = 'Meteoric';
              notif.show();
            } else {
              window.webkitNotifications.requestPermission($jy.notify);
            }
          }
          else if ("Notification" in window) {
            // 判断是否有权限
            if (Notification.permission === "granted") {
              var notification = new Notification(title, {
                "icon": iconUrl,
                "body": content
              });
            }
            //如果没权限，则请求权限
            else if (Notification.permission !== 'denied') {
              Notification.requestPermission(function (permission) {
                // Whatever the user answers, we make sure we store the
                // information
                if (!('permission' in Notification)) {
                  Notification.permission = permission;
                }
                //如果接受请求
                if (permission === "granted") {
                  var notification = new Notification(title, {
                    "icon": iconUrl,
                    "body": content
                  });
                }
              });
            }
          }
        }

        MessageBus.start(); // call once at startup
        MessageBus.callbackInterval = 500;
        channel = '/channel';
        window.roomid = "<%= current_user.private_token %>";
        if (window.roomid) {
          channel = channel + '/' + window.roomid;
        }
        MessageBus.subscribe(channel, function (data) {
          $('.badge-notify-count').text(data.count);
          notify(data.content);
          $('#content').val('');
        });
      })
    </script>
<% end %>

</body>
</html>