config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  devise_for :users, path: 'account', controllers: {
      sessions: 'users/sessions', registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords'
  }
  mount RuCaptcha::Engine => '/rucaptcha'
  resources :accounts, only: [:new, :create, :destroy] do
    collection do
      get :register
      post :register_post
      post :validate_captcha
      get :forget_password
      get :reset_password
      post :reset_password_post
      post :send_code
      post :register_email_exists
      post :register_mobile_exists
      post :register_nickname_exists
    end
  end

  get 'user' => redirect('/user/preview')

  match 'user/preview' => 'user#preview', as: 'user_preview', via: [:get, :post]
  match 'user/profile' => 'user#profile', as: 'user_profile', via: [:get, :post]
  match 'user/update_avatar' => 'user#update_avatar', as: 'user_update_avatar', via: [:post]
  match 'user/remove_avatar' => 'user#remove_avatar', as: 'user_remove_avatar', via: [:post]
  match 'user/passwd' => 'user#passwd', as: 'user_passwd', via: [:get, :post]
  match 'user/reset_mobile' => 'user#reset_mobile', as: 'user_reset_mobile', via: [:get, :post]
  match 'user/reset_email' => 'user#reset_email', as: 'user_reset_email', via: [:get, :post]
  match 'user/send_email_code' => 'user#send_email_code', as: 'user_send_email_code', via: [:post]
  match 'user/send_add_mobile_code' => 'user#send_add_mobile_code', as: 'user_send_add_mobile_code', via: [:post]
  match 'user/comp' => 'user#comp', as: 'user_comp', via: [:get]
  match 'user/consult' => 'user#consult', as: 'user_consult', via: [:get, :post]
  match 'user/point' => 'user#point', as: 'user_point', via: [:get, :post]
  match 'user/add_point' => 'user#add_point', as: 'user_add_point', via: [:get, :post]
  match 'user/notification' => 'user#notification', as: 'user_notification', via: [:get]
  get '/user/notify' => 'user#notify_show'
  match '/user/add_school' => 'user#add_school', as: 'user_add_school', via: [:post]


  # mount ActionCable.server => '/cable'
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
  end

  # 验证邮箱是否已经注册
  def register_email_exists
    result = User.where(email: params[:email]).exists?
    render json: result
  end

  # 验证手机是否已经注册
  def register_mobile_exists
    result = User.where(mobile: params[:mobile]).exists?
    render json: result
  end

  # 验证昵称是否已经注册
  def register_nickname_exists
    result = User.where(nickname: params[:nickname]).exists?
    render json: result
  end

  def register
    if current_user.present?
      redirect_to root_path
      return
    end
    @sing_up = SingUp.new
  end

  def register_post
    if current_user.present?
      redirect_to root_path
      return
    end
    s_u = params[:sing_up]
    @sing_up = SingUp.new(mobile: s_u[:mobile], mobile_code: s_u[:mobile_code], nickname: s_u[:nickname], password: s_u[:password])
    user = @sing_up.save
    if user.present?
      flash[:success] = '注册成功,请登录!'
      redirect_to_url
    else
      render :register
    end
  end

  def reset_password
    if current_user.present?
      redirect_to root_path
      return
    end
    @reset_password = ResetPassword.new
  end

  def reset_password_post
    if current_user.present?
      redirect_to root_path
      return
    end
    r_p = params[:reset_password]
    @reset_password = ResetPassword.new(mobile: r_p[:mobile], mobile_code: r_p[:mobile_code], password: r_p[:password])
    if @reset_password.save
      flash[:success] = '密码已经成功重置'
      redirect_to root_path
    else
      render :reset_password
    end
  end

  def validate_captcha
    if request.method == 'POST'
      if verify_rucaptcha? params[:_rucaptcha]
        result = [true, '校验码正确']
      else
        result = [false, '校验码输入错误']
      end
    else
      result = [false, '非法请求']
    end
    render json: result
  end

  def send_code
    if params[:type].present? && params[:mobile].present?
      sms = SMSService.new(params[:mobile])
      data = sms.send_code(params[:type], request.ip)
    else
      data = [false, '信息不完整']
    end
    render json: data
  end

  private

  def redirect_to_url
    if cookies[:redirect_url].present?
      redirect_url = cookies[:redirect_url]
      cookies[:redirect_url] = nil
      redirect_to redirect_url
    else
      redirect_to root_path
    end
  end
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < AdminController

  skip_before_action :authenticate, only: [:new, :create, :destroy]
  layout 'admin_boot'

  def new
  end

  def index
    redirect_to '/admin/'
  end

  def create
    if verify_rucaptcha? params[:_rucaptcha]
      emp = Admin.find_by(job_number: params[:job_number])
      # cookies[:job_number] = params[:job_number]
      if emp.blank?
        flash[:error] = '工号不存在'
        render action: 'new'
      elsif not emp.auth_permissions(['admin', 'super_admin', 'teacher', 'audit', 'score', 'super_editor' 'editor'])
        flash[:error] = '此账号没有权限登录'
        render action: 'new'
      else
        status, message = emp.login(params[:password], request.remote_ip)
        if status
          flash[:notice] = message
          sing_in(emp)
          redirect_to '/admin/'
        else
          flash[:error] = message
          render action: 'new'
        end
      end
    else
      flash[:error] = '校验码不正确'
      render action: 'new'
    end
  end

  def destroy
    # sign_out
    # redirect_to root_path
    sing_out
    flash[:error] = '您已成功退出'
    redirect_to action: :new
  end

  def change_password
    render :layout => 'admin'
  end

  def change_password_post
    status, message = self.change_password_method(@current_admin, params[:password], params[:new_password], params[:confirm_password])

    if status
      session[:admin_id] = nil
      flash[:success] = message
      redirect_to action: :new
    else
      flash[:error] = message
      redirect_to action: :change_password
    end
  end

  def change_password_method(current_admin, old_password, new_password, confirm_password)
    unless current_admin.present?
      return [FALSE, '用户不存在']
    end
    unless old_password.present?
      return [FALSE, '原密码不能为空']
    end
    unless new_password.length >= 6 && new_password.length <= 20
      return [FALSE, '请输入6-20位新密码']
    end
    unless new_password == confirm_password
      return [FALSE, '新密码两次输入不一致']
    end
    unless current_admin.authenticate(old_password)
      return [FALSE, '原密码不正确']
    end

    if current_admin.authenticate(old_password) && (current_admin.password = new_password; current_admin.save)
      [TRUE, '密码已成功修改，请重新登录']
    else
      [FALSE, '密码修改过程出错']
    end
  end


  private

  def sing_in(emp)
    cookies[:access_token] = emp.access_token
  end

  def sing_out
    cookies[:access_token] = nil
  end
end

app/views/accounts/register.html.erb
<div class="container">

  <div class="row">
    <div class="passport">

      <div class="col-sm-4 col-md-4">
        <h2 class="text-center">注册</h2>
        <%= simple_form_for(@sing_up, url: register_post_accounts_path, method: :post) do |f| %>
            <div class="text-right">没有手机？请用<a class="blue" href="/account/sign_up">邮箱</a>注册<br/>
            </div>
            <%= f.input :nickname, as: :tel, placeholder: '请输入昵称' %>
            <%= f.input :password, placeholder: '请输入至少6位密码', wrapper_html: {class: ''} %>

            <div class="form-group">
              <div class="row">
                <div class="col-xs-12">
                  <div class="row">
                    <div class="col-xs-7">
                      <div class="form-group string">
                        <%= rucaptcha_input_tag(class: 'form-control ', placeholder: '请输入校验码') %>
                      </div>
                    </div>
                    <div class="col-xs-5">
                      <span class="refresh-captcha">
                        <%= rucaptcha_image_tag(alt: '校验码', id: 'rucaptcha-image-style') %>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="input-group form-group required sing_up_mobile">

              <input id="sing_up_mobile" class="string tel required form-control" type="tel" name="sing_up[mobile]" value="<%= @sing_up.mobile %>" placeholder="请输入手机号">
              <span class="input-group-addon btn btn-default" id="btn_send_mobile_code" data-key="sing_up" data-type="REGISTER">发送验证码</span>
            </div>

            <%= f.input :mobile_code, as: :tel, placeholder: '请输入手机验证码' %>

            <div class="form-group form-group-lg">
              <%= f.submit class: 'btn btn-primary btn-block', value: '立即注册', 'data-disable-with' => '正在注册' %>
            </div>
        <% end %>
        <p class="clearfix text-right">
          <a href="<%= new_user_session_path %>">使用已有账户登录</a>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/accounts/reset_password.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-md-4">
      <h2 class="text-center">重置密码</h2>
      <%= simple_form_for(@reset_password, url: reset_password_post_accounts_path, method: :post) do |f| %>
          <%= f.input :password, label: '新密码', placeholder: '请输入至少6位新密码', wrapper_html: {class: ''} %>

          <div class="form-group">
            <div class="row">
              <div class="col-xs-12">
                <div class="row">
                  <div class="col-xs-7">
                    <div class="form-group string">
                      <%= rucaptcha_input_tag(class: 'form-control ', placeholder: '请输入校验码') %>
                    </div>
                  </div>
                  <div class="col-xs-5">
                      <span class="refresh-captcha">
                        <%= rucaptcha_image_tag(alt: '校验码', id: 'rucaptcha-image-style') %>
                      </span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="input-group form-group required reset_password_mobile">

            <input id="reset_password_mobile" class="string tel required form-control" type="tel" name="reset_password[mobile]" value="<%= @reset_password.mobile %>" placeholder="请输入手机号">
            <span class="input-group-addon btn btn-default" id="btn_send_mobile_code" data-key="reset_password" data-type="RESET_PASSWORD">发送验证码</span>

          </div>
          <% if @reset_password.errors[:mobile].present? %>
              <span class="help-block" style="color: darkred"><%= @reset_password.errors[:mobile].last %></span>
          <% end %>

          <%= f.input :mobile_code, as: :tel, placeholder: '请输入手机验证码' %>
          <div class="form-group form-group-lg">
            <%= f.submit class: 'btn btn-warning btn-block', value: '重置密码', 'data-disable-with': '正在提交' %>
          </div>
      <% end %>
      <p class="clearfix text-right">
        <a class="exchange-mobile" href="<%= new_user_password_path %>">使用邮箱重置</a>
      </p>
    </div>
  </div>
</div>